export const SUBMIT_FORM_REQUEST = 'SUBMIT_FORM_REQUEST';
export const SUBMIT_FORM_SUCCESS = 'SUBMIT_FORM_SUCCESS';
export const SUBMIT_FORM_FAILURE = 'SUBMIT_FORM_FAILURE';
export const UPDATE_VEHICLE_AGE = 'UPDATE_VEHICLE_AGE';
export const OBTAIN_IP_ADDRESS = 'OBTAIN_IP_ADDRESS';
