export const SUBMIT_FORM_REQUEST = 'SUBMIT_FORM_REQUEST';
export const SUBMIT_FORM_SUCCESS = 'SUBMIT_FORM_SUCCESS';
export const SUBMIT_FORM_FAILURE = 'SUBMIT_FORM_FAILURE';
export const UPDATE_VEHICLE_YEAR = 'UPDATE_VEHICLE_YEAR';
export const IP_ADDRESS_REQUEST = 'IP_ADDRESS_REQUEST';
export const IP_ADDRESS_SUCCESS = 'IP_ADDRESS_SUCCESS';
export const RESET_SUBMITTED = 'RESET_SUBMITTED';
